    <main>
        <table>
            <thead>
                <tr>
                    <th>ID</th>
                    <th>Name</th>
                    <th>Gender</th>
                    <th>Email</th>
                    <th>SDT</th>
                    <th>Role</th>
                    <th>Password</th>
                    <th>Province</th>
                </tr>
            </thead>
            <tbody>
                <tr>
                    <td>1</td>
                    <td>Jonse</td>
                    <td>Female</td>
                    <td>jonse@gmail.com</td>
                    <td>0123456789</td>
                    <td>Client</td>
                    <td>123</td>
                    <td>HN</td>
                </tr>
            </tbody>
        </table>
    </main>
</div>